### ISSUE TITLE
Migrate a reasonably-sized application to a Modulith

### ISSUE THREAD

**Issue by thombergs** [odrotbohm/moduliths#11]
In order to get some real-world experience, we should migrate a Spring Boot app with more than a couple hundred lines of code to a Modulith. For this to work, the library must have matured a bit and at least a snapshot should be released to Maven Central or JCenter.

**Comment by odrotbohm** [comment]
I think we can cross this off as we're 10 GA now and there are a couple of projects already using the library, most notably [Quarano](https://github.com/quarano/quarano-application) on the open-source side.
