### ISSUE TITLE
Issues using the ModuleDetection SPI

### ISSUE THREAD

**Issue by OLibutzki** [odrotbohm/moduliths#147]
While implementing a customized _ModuleDetectionStrategy_ I stumbled upon [JavaPackage#getClasses()](https://github.com/odrotbohm/moduliths/blob/b46966565975df00ad9fcbaec558d9b7ce9bd0a6/moduliths-core/src/main/java/org/moduliths/model/JavaPackage.java#L94). _JavaPackage_ and the _getClasses()_ method are public, but the return type_Classes_ itself is package protected.

This constraint leads to the restriction that I cannot use classes to detect a module.

Moreover I felt the desire to use the underlying ArchUnit API directly for detecting modules. I am sure that it's intended to have some abstraction like _JavaPackage_ and _Classes_, but in the bootstrapping process of detecting modules a low level API might be the better choice in order to allow more sophisticated detection strategies.

**Comment by odrotbohm** [comment]
Would you be fine if we simply made `Classes` public?

**Comment by OLibutzki** [comment]
> Would you be fine if we simply made `Classes` public?

I'm not sure about that, but I will check it.

**Comment by odrotbohm** [comment]
Any feedback on this? I would like to get to an RC relatively soon and make sure the `ModuleDetectionStrategy` SPI is really useful.

**Comment by odrotbohm** [comment]
I've made `Classes` public and also exposed the `….stream()` method for now.

**Comment by OLibutzki** [comment]
To be honest I did not find the time to try it in depth, but it look good to me.

`org.moduliths.model.JavaPackage.that(DescribedPredicate<? super JavaClass>)` provides a way to use the ArchUnit Core API to detect modules and `org.moduliths.model.Classes.stream()` provides a way to iterate these modules and map them using _org.moduliths.model.JavaPackage.of(Classes, String)_.

This code (which should do the same as _org.moduliths.model.ModuleDetectionStrategies.EXPLICITLY_ANNOTATED_) compiles now and therefore I'm optimistic that it's possible to implement any mdoule detection strategy:
public class MarsModuleDetectionStrategy implements ModuleDetectionStrategy {

```
	@Override
	public Stream<JavaPackage> getModuleBasePackages( final JavaPackage basePackage ) {
		final Classes classes = basePackage.getClasses( );
		return basePackage.that( JavaClass.Predicates.simpleName( "package-info" )
				.and( CanBeAnnotated.Predicates.annotatedWith( Module.class ) ) ).stream( )
				.map( JavaClass::getPackageName ) 
				.distinct( )
				.map( it -> JavaPackage.of( classes, it ) );
	}
}
```
