### ISSUE TITLE
Add an `Automatic-Module-Name` in the jar(s) MANIFEST

### ISSUE THREAD

**Issue by sebastienh** [odrotbohm/moduliths#161]
Hi!

I made the same request in the jMolecules project but I also want to use moduliths library.. I would like to use Moduliths in an Intellij Java project which uses Java 9 modules. The problem is that if a library doesn't declare an Automatic-Module-Name in the Jar MANIFEST the library falls into the unnamed module, and as we speak, Intellij does not support unnamed module.

Thanks again for this(ese) library!

**Comment by odrotbohm** [comment]
That should be in place now.
