### ISSUE TITLE
Unable to use moduliths-events-starter

### ISSUE THREAD

**Issue by dsarlo-viso** [odrotbohm/moduliths#171]
Parameter 0 of constructor in org.moduliths.events.jpa.JpaEventPublicationConfiguration required a bean of type 'org.moduliths.events.jpa.JpaEventPublicationRepository' that could not be found.

Spring Boot Version 2.4.4, Also tried downgrading to 2.3.10 with no luck.

The following issue solution did not help either:
Upgrading to `1.1.0-RC2` solved the issue.

_Originally posted by @igler in https://github.com/odrotbohm/moduliths/issues/166#issuecomment-818947681_

Getting this with all versions of the library when starting my application. Any assistance would be greatly appreciated @odrotbohm

**Comment by odrotbohm** [comment]
Sorry for the inconvenience, Dan. Do you have a sample project showing the error. There's a [sample project|https://github.com/odrotbohm/spring-events-deep-dive] that definitely builds fine (including tests) when you include the currently commented out dependency to `moduliths-events-starter`. Would you mind trying the latest snapshots, too?

**Comment by dsarlo-viso** [comment]
> Sorry for the inconvenience, Dan. Do you have a sample project showing the error. There's a [sample project|https://github.com/odrotbohm/spring-events-deep-dive] that definitely builds fine (including tests) when you include the currently commented out dependency to `moduliths-events-starter`. Would you mind trying the latest snapshots, too?

I appreciate the reply! Yeah I was taking a look at that project after seeing you use it on a Tanzu Tuesdays video. I'll give the latest snapshots a try quickly.

**Comment by odrotbohm** [comment]
I just checked the setup of the auto-configuration we deploy here: it assumes – if you use Spring Boot – that Spring Data JPA repositories are enabled. If you don't use Spring Boot it automatically enables it for the necessary packages. Any chance that you run a Boot app with SD JPA on the classpath but repositories disabled?

**Comment by dsarlo-viso** [comment]
> I just checked the setup of the auto-configuration we deploy here: it assumes – if you use Spring Boot – that Spring Data JPA repositories are enabled. If you don't use Spring Boot it automatically enables it for the necessary packages. Any chance that you run a Boot app with SD JPA on the classpath but repositories disabled?

Sadly that is not the case. We do enable JPA repositories and have the jpa starter on the classpath

```
@EnableJpaRepositories("com.etc") - In configuration file

implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
```

**Comment by odrotbohm** [comment]
Let's tackle this, one by one: if you use `@EnableJpaRepositories` explicitly, you *completely* disable Boot's auto-configuration for JPA and Spring Data JPA repositories. That means that repositories and entities are *only* picked up from packages you define. Can you try adding `org.moduliths.events.jpa` to the list of packages you declare explicitly?

Regarding the "non-public interface is not defined by the given loader" I'll have to investigate. Is DevTools in play here by accident? I've experienced the classloader arrangement causing a few issues here and there.

**Comment by dsarlo-viso** [comment]
> Let's tackle this, one by one: if you use `@EnableJpaRepositories` explicitly, you _completely_ disable Boot's auto-configuration for JPA and Spring Data JPA repositories. That means that repositories and entities are _only_ picked up from packages you define. Can you try adding `org.moduliths.events.jpa` to the list of packages you declare explicitly?
> 
> Regarding the "non-public interface is not defined by the given loader" I'll have to investigate. Is DevTools in play here by accident? I've experienced the classloader arrangement causing a few issues here and there.

Thank you for this. I tried adding `org.moduliths.events.jpa` to the list of packages specified for `@EnableJpaRepositories`. Spring was able to find the Repository exposed by the Moduliths package, however, I am now receiving the same issue as before "non-public interface is not defined by the given loader". We are using DevTools locally. I also tried removing it from the project, but I am still seeing the same issue persist.

**Comment by dsarlo-viso** [comment]
@odrotbohm Thank you for #171. I'll try the snapshot in a bit. 

Without dev tools, I created the table and everything seems fine, however, with jpa show-sql, nothing is ever being persisted to the jpa_event_publication table. I only ever see the lookup for null completion_date happen to the jpa_event_publication table.

**Comment by odrotbohm** [comment]
I've fixed the issue with DevTools. If you're not using automatic schema creation with Hibernate, you'd have to take care of the schema creation for the publication table yourself. I guess you can mimic what Hibernate is doing, enable SQL logging in a sample project and just copy the output into a Flyway script or the like for now. I'd like to focus this ticket on the DevTools aspect and mark this resolved. We of course need to improve on the schema creation but that's likely much more effort as we have to provide this for multiple databases etc., which warrants a new ticket.

Regarding the actual interaction with the database, I'd have to again ask for a reproducing example as "nothing is ever being persisted" can't really be investigated without one and we have tests and samples (one linked to above), that actually show the interaction happening and the log working.

**Comment by odrotbohm** [comment]
See #172 for the schema creation aspect.
