### ISSUE TITLE
Allow tweaking the default output directory for documentation generation

### ISSUE THREAD

**Issue by jamietanna** [odrotbohm/moduliths#212]
In #112, we set the output directory to `target`, but when using a Gradle project, this doesn't line up with the `.gitignore`'d directory `build`, and doesn't follow where it would generally be expected to be.

**Comment by odrotbohm** [comment]
I agree, we should expose configuration API to tweak the output folder for documentation generation.

**Comment by odrotbohm** [comment]
I've tweaked the general default to `build/moduliths-docs` in case we detect a Gradle project (lacking a `pom.xml` in the project root). I also introduced the option on `Documenter` to customize the output folder entirely, too.
